def init():
    FRAME_SIZE = 5
    SIMULATION_LENGTH = 500
    SIMULATIONS = 100

    # OPTIMAL SIMULATION FOR GREATEST THROUGHPUT / CAPACITY
    SLOTTED_PROBABILITY = 0.75
    PURE_PROBABILITY = 0.1

    # SLOTTED THROUGHPUT
    # SLOTTED_PROBABILITY = 0.75
    # PURE_PROBABILITY = 0.75

    # PURE THROUGHPUT
    # SLOTTED_PROBABILITY = 0.1
    # PURE_PROBABILITY = 0.1
    global FRAME_SIZE, SIMULATION_LENGTH, SIMULATIONS, SLOTTED_PROBABILITY, PURE_PROBABILITY

